### ISSUE TITLE
Controller Version: 6.0.20 

### ISSUE THREAD

**Issue by michaelpietzsch** [unifi-poller/dashboards#12]
Hello,

i've been testing everything with 6.0.20 and there is a lot of information missing. Client DPI

**Comment by davidnewhall** [comment]
DPI must be enabled on the controller and in the poller config. Two spots. Please share your configuration for poller if you're unable to get that working.

**Comment by michaelpietzsch** [comment]
@davidnewhall  thanks for the quick reply. Are there ENV Variables to enable this  "UP_SAVE_DPI" or something similar?

**Comment by davidnewhall** [comment]
That's correct. All of the env variables are documented on the [Configuration](https://github.com/unifi-poller/unifi-poller/wiki/Configuration) page in the wiki.
