### ISSUE TITLE
No data in UniFi / UniFi-Poller: Client DPI - InfluxDB

### ISSUE THREAD

**Issue by einsteinagogo** [unifi-poller/dashboards#13]
No data in UniFi / UniFi-Poller: Client DPI - InfluxDB

All the other Dashboards are populated.

Any clues ?

**Comment by davidnewhall** [comment]
DPI has to be turned on in your controller and in poller. Two spots.

**Comment by einsteinagogo** [comment]
Good Catch, it is already on in the controller.

But not in the poller. let me change that.

**Comment by einsteinagogo** [comment]
dpi = true!

fixed.
