### ISSUE TITLE
UniFi-Poller: Client DPI - InfluxDB - No data

### ISSUE THREAD

**Issue by lslamp** [unifi-poller/dashboards#14]
Just installed "UniFi-Poller: Client DPI - InfluxDB" and I have no data in any of the graphs. I do have DPI switched on in unifi.

All the other dashboards work great.

Lawrence

**Comment by davidnewhall** [comment]
You have it disabled in your poller config according to an issue you opened previously. `save_dpi=true`

**Comment by lslamp** [comment]
Working ... yet again you rescue the day Thanks
