### ISSUE TITLE
Unit 'farenheit' is not supported

### ISSUE THREAD

**Issue by dpackham** [unifi-poller/dashboards#2]
in the US and have the USW Insights dashboard loaded and I get the above error on the "Switch Temperature"

![Untitled](https://user-images.githubusercontent.com/707522/72851605-4b40ec00-3c69-11ea-86ad-07d7956c97bd.png)

**Comment by davidnewhall** [comment]
Grafana changed the spelling of `Fahrenheit`. Easy fix: Edit the graph, go to visualizations and fix the unit. Set it to fahrenheit.

**Comment by dpackham** [comment]
Yup.  it was cleared and I reselected fahrenheit and it works now

**Comment by davidnewhall** [comment]
This issue comes up once in a while so I'm going to re-open this for a while, so it's easier for others to find. I'll close it some time after v2 releases, and all the dashboards get updated to Grafana 6.5.

**Comment by davidnewhall** [comment]
v2 is out. check it out!
