### ISSUE TITLE
UniFi Client DPI: InfluxDB Dashboard

### ISSUE THREAD

**Issue by jkosharek** [unifi-poller/dashboards#3]
Just setup and installed unifi-poller, grafana, and influxDB and imported 'UniFi Client DPI: InfluxDB Dashboard' Imported fine but nothing will load, the "site" selection is empty. All of the other dashboards on "https://grafana.com/grafana/dashboards?dataSource=influxdb&search=unifi-poller" are working ok but not this one.

I am running this against an UDM-PRO, maybe something to do with the way it handles sites?

**Comment by davidnewhall** [comment]
It sounds like your configuration may be incorrect. Can you share your config?

**Comment by jkosharek** [comment]
In the up.conf I changed the values for user and pass.


Joe Kosharek | joe@kosharek.com<mailto:joe@kosharek.com> | I.T. Infrastructure | (727) 423-0040

**Comment by davidnewhall** [comment]
Set `save_sites` to `true` as well. That should take care of it.

**Comment by jkosharek** [comment]
That was already set to true.
I changed  sites  = ["all"] to   = ["default"] and it seems to have fixed it.

How long is the data stored in InfluxDB, is there a setting for purging data?

Joe Kosharek | joe@kosharek.com<mailto:joe@kosharek.com> | I.T. Infrastructure | (727) 423-0040

**Comment by davidnewhall** [comment]
Glad you got it working!

InfluxDB will, by default, store data forever. You can adjust that using retention policies. This document provides more information. https://docs.influxdata.com/influxdb/v1.7/query_language/database_management/

**Comment by davidnewhall** [comment]
Also, I typo'd and I'm not sure if you saw the corrected/edited message. I meant `save_dpi` not `save_sites`.

**Comment by jkosharek** [comment]
That makes sense, after reading the example config all the way through, I changed my setting to this:
[cid:image002.jpg@01D5EB23.3D094CA0]


Thanks for your help!

Joe Kosharek | joe@kosharek.com<mailto:joe@kosharek.com> | I.T. Infrastructure

**Comment by davidnewhall** [comment]
You're very welcome! Enjoy the new data!
