### ISSUE TITLE
No data being pulled - Dream Machine Pro

### ISSUE THREAD

**Issue by andrewjmoser** [unifi-poller/dashboards#4]
Running this dashboard, and have DPI enabled, but no data is populating.  All the other Unifi Poller dashboards are working fine.   I'm using InfluxDB.

**Comment by davidnewhall** [comment]
DPI needs to be enabled on your control and in the poller configuration. If you've done this, please share your configuration and the output from the application.

**Comment by andrewjmoser** [comment]
It's working, I missed the line in the Poller config file to enable that feature.   Thanks!
