### ISSUE TITLE
Client DPI does not load any data

### ISSUE THREAD

**Issue by thegreyfox** [unifi-poller/dashboards#6]
Hi, I just installed your unifi-poller (influxdb) and the rest of the charts work fine, except for the Client-DPI (#10419). 

Am i missing anything here? 

Nothing loads and it just says No data to show.

Let me know what other information you require :)

**Comment by davidnewhall** [comment]
You must enable DPI on the controller and in the poller config. Two spots.

**Comment by thegreyfox** [comment]
Hi David

Thanks for the response.

DPI has all along been enabled on the controller though.

When you mentioned poller config, where exactly is this setting at?

**Comment by davidnewhall** [comment]
Show me your current config.

**Comment by thegreyfox** [comment]
Hi David

Thanks. Realised I didn’t add the environments for DPI. It’s now working. Just want to let you know that this dashboard of yours is truly amazing! Keep up the fantastic work!

**Comment by davidnewhall** [comment]
Sweet!
