### ISSUE TITLE
Client DPI Dashboard Loads No Data

### ISSUE THREAD

**Issue by cmoskowitz** [unifi-poller/dashboards#7]
I have loaded all unifi-poller dashboards and all of them work excellent except the client DPI dashboard doesn't work.  No data gets loaded.

**Comment by jonbloom** [comment]
Make sure you have enabled DPI in your controller, as well as your UniFi Poller config.

See [here](https://github.com/unifi-poller/unifi-poller/wiki/Configuration#input-unifi).

**Comment by cmoskowitz** [comment]
It is enabled.  This is the udm pro, I can see the dpi data in unifi just not your dashboard.

**Comment by davidnewhall** [comment]
Show me.

**Comment by cmoskowitz** [comment]
David,

Want to see the dpi configuration on my device and the empty dashboards?

**Comment by davidnewhall** [comment]
I'd like to see the configuration for poller and the output while it's running. Thanks.

**Comment by cmoskowitz** [comment]
On my phone at the moment where and what configuration would you like to see here are two screenshots

**Comment by davidnewhall** [comment]
The poller config is either a config file or environment variables. Depends on how you are running it. Please provide all configuration you're passing to the application. Poller outputs data when you run it. Should be saved to a log file or docker logs (depend how you installed it). Please share this data so we can give you steps on how to enable DPI.

**Comment by cmoskowitz** [comment]
Thank you, here are all configs, they are running in dockers.

**Comment by davidnewhall** [comment]
Please click this link: https://github.com/unifi-poller/dashboards/issues/7
And add the data you attempted to add previously. Thanks!

**Comment by cmoskowitz** [comment]
I’m confused, the link brings me back to our discussion.

**Comment by cmoskowitz** [comment]
<img width="1145" alt="grafana confi" src="https://user-images.githubusercontent.com/66876093/84594700-23be0c00-ae22-11ea-96ad-9c6d141f8268.png">
<img width="833" alt="influx db" src="https://user-images.githubusercontent.com/66876093/84594701-24ef3900-ae22-11ea-9b30-956f68c0b05b.png">
<img width="825" alt="poller config" src="https://user-images.githubusercontent.com/66876093/84594703-27519300-ae22-11ea-97af-1ef1c116805f.png">

**Comment by davidnewhall** [comment]
If you add `UP_UNIFI_DEFAULT_SITE_IDS=true` to `the golift-unifi-poller1` definition it should solve your issue.

**Comment by cmoskowitz** [comment]
thanks David, I changed that and it still not working.  Maybe it takes a 
while to start collecting data?  Do the environment variables matter in 
terms of their respective order they are put in?

**Comment by davidnewhall** [comment]
Sorry I typo'd,. it's `UP_UNIFI_DEFAULT_SITE_DPI=true`

**Comment by davidnewhall** [comment]
Can you upgrade to the latest version and show me the poller output on startup? And a fresh screenshot of your poller config.

**Comment by Dreded** [comment]
Having the same issue just confirming that a usg is also required for this data?
I don't have a Unifi Security Gateway

**Comment by davidnewhall** [comment]
@Dreded,
I believe a UniFi Gateway is necesarry. Do you see DPI data in the controller web UI? Have you enabled DPI in the controller and in the poller config?

**Comment by jonbloom** [comment]
@davidnewhall @Dreded You need a UniFi Gateway for DPI to function. Either a USG or UDM [pro]

**Comment by cmoskowitz** [comment]
I have a udm pro and dpi is enabled in the UI.

**Comment by cmoskowitz** [comment]
I have a udm pro and dpi is enabled in the UI and the dash still doesn’t work but all others do.

**Comment by jonbloom** [comment]
@cmoskowitz Did you enable the configuration for poller to pull DPI? It needs to be enabled in both places.

**Comment by cmoskowitz** [comment]
Yes.  Can you send me the poller variable?  Maybe I have a typo.

**Comment by jonbloom** [comment]
It's `UP_UNIFI_DEFAULT_SAVE_DPI`. Set it to `true`.

**Comment by davidnewhall** [comment]
Y'all OK now?
