### ISSUE TITLE
Sites will not populate in Client DPI

### ISSUE THREAD

**Issue by Jporterz28** [unifi-poller/dashboards#9]
I'm new to Grafana, and actually Unifi as well, I've loaded 4 of the other dashboards and all work well.  The Client DPI dashboard is not populating the Sites menu.  I'm running the latest Grafana 7.0.3_armhf on a Raspberry Pi 4, using InfluxDB, not sure the version there. Of course, since there is no site selected, it shows no data available.
Thanks for listening to my newb-ness!

**Comment by davidnewhall** [comment]
You need to enable DPI on the controller and in the poller config. Two spots.

**Comment by davidnewhall** [comment]
Did you figure it out?

**Comment by Jporterz28** [comment]
Yes! Thanks for following up.  I went through everything again, and I think
the issue was that I was restarting Grafana instead of UniFi-poller after
enabling DOI in the config file.  Just a bit of confusion on my end.
